# Generated by Django 4.0.6 on 2022-07-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
