# Generated by Django 4.0.6 on 2022-07-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotitas', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
