# Generated by Django 4.0.6 on 2022-07-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='imagen_blog',
        ),
    ]
